### ISSUE TITLE
Prision Break | Erfahrungsaustausch rund um den Ausbruch aus Vendor Lock-In

### ISSUE THREAD

**Issue by MichelHartmann** [dcnc-eu/cloudcamp-2023#10]
Immer wieder reden wir über Vendor-Lock-In. Meist geht es aber dann darum, dass er böse ist und wie der Teufel gemieden werden sollte. Wenn man aber einen Plan hat, wie man sich aus dem eisernen Griff befreit und mit welchen Kosten dieser Schritt verbunden wäre, kann man den Lock-In auch bewusst in Kauf nehmen und von den Vorteilen profitieren.

In dieser Session werden wir uns über Erfahrungen austauschen, wie wir den einen oder anderen Vendor Lock-In verlassen können. Gerne werde ich hier auch unsere Erfahrungen bei FLYERALARM teilen, wo wir recht aktuell das Thema haben, 2.000 Repositories von Bitbucket und Bamboo wegzumigrieren.

Mit dem geteilten Wissen wollen wir uns gegenseitig wappnen, den nächsten potenziellen Vendor Lock-In bewusster zu behandeln.

**Comment by heubeck** [comment]
Überlappungen mit https://github.com/dcnc-eu/cloudcamp-2023/issues/9
Join forces?
