### ISSUE TITLE
Landing Zones mit AWS

### ISSUE THREAD

**Issue by raupachz** [dcnc-eu/cloudcamp-2023#11]
Wir würden uns gerne über das Thema Landing Zones austauschen. Für uns ist eine Landing Zone ein eigenständiger AWS Account für einen Workload. In der Regel umfasst der Workload die Entwicklung, Betrieb und Monitoring einer Anwendung. Jede Landing Zone gehört einem Development Team. Es ist ein reiner DevOps-Ansatz.

Themen wären:
- AWS Organizations
- VPC Peering
- CloudWatch
- ECS
- Identity Center (SSO)
- und wie könnte es anders sein: IAM

Anmerkung: wir verwenden kein AWS Control Tower

**Comment by schroedjan** [comment]
Hey, das Thema klingt interessant!

Wir fahren ein ähnliches Prinzip und verwenden ebenfalls (bewusst) kein AWS Control Tower.

Wir setzen allerdings zusätzlich zur reinen LandingZone (AWS Account) noch eine Baseline von Standard Ressourcen (Network, Security, ...) und eine komplett automatisierte Supply-Chain mit Terraform auf.
Das DevOps-Team kann somit in definierten Workflows direkt mit der Entwicklung einer Applikation beginnen.

Die Idee dahinter ist, neben der Standardisierung, den DevOps Teams eine möglichst geringe Hürde für die Entwicklung in der Cloud zu geben.

Gerne können wir hier unsere Ansätze und Erfahrungen einbringen und diskutieren!
