### ISSUE TITLE
Der DevOps-Buchclub

### ISSUE THREAD

**Issue by heubeck** [dcnc-eu/cloudcamp-2023#14]
Gene Kim beschreibt in seinen Büchern "The Phoenix Project" und "The Unicorn Project" die Transformation eines fiktiven Unternehmens von abgeschotteten Silos hin zu einer funktionierenden DevOps-Organisation. Das Ganze ist allerdings nicht komplett fiktional, sondern basiert auf Erkenntnissen, die Gene Kim während seiner eigenen Forschungsarbeit gesammelt hat.

Wir diskutieren gemeinsam Best Practices einer DevOps-Transformation auf Basis der beiden Bücher und eigenen Erfahrungen der Teilnehmer - denn sind wir mal ehrlich: Nach spätestens 10 Seiten hat sich jeder im Buch selbst wiedergefunden. Wie viel Parts Unlimited seid ihr?

Kenntnis der Bücher ist dringend empfohlen!

**Comment by stuebingerb** [comment]
CloudLand 2023 is over
